# Generated by Django 4.2.4 on 2023-08-16 12:37

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[profiles.validators.only_alpha_characters_validator], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=45, verbose_name='Email')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), profiles.validators.contains_digit_validator], verbose_name='Password')),
            ],
        ),
    ]
