# Generated by Django 4.2.4 on 2023-08-17 12:31

from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(validators=[events.validators.validate_date], verbose_name='Date'),
        ),
    ]
